In [1]:
import pandas as pd

In [11]:
for i in range(0, 19):
    file_path = fr'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 ({i}).csv'
    print(f"df_{i} = pd.read_csv(r'{file_path}',parse_dates=['Date'], dayfirst=True )")

df_0 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (0).csv',parse_dates=['Date'], dayfirst=True )
df_1 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (1).csv',parse_dates=['Date'], dayfirst=True )
df_2 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (2).csv',parse_dates=['Date'], dayfirst=True )
df_3 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (3).csv',parse_dates=['Date'], dayfirst=True )
df_4 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (4).csv',parse_dates=['Date'], dayfirst=True )
df_5 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (5).csv',parse_dates=['Date'], dayfirst=True )
df_6 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (6).csv',parse_dates=['Date'], dayfirst=True )
df_7 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (7).csv',parse_dates=['Date'], dayfirst=True )
df_8 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (8).csv',parse_dates=['Date'], dayfirst=True )
df_9 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (9).csv',parse_dates=['Date'], dayfirst=True )
df_10 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (10).csv',parse_dates=['Date'], dayfirst=True )
df_11 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (11).csv',parse_dates=['Date'], dayfirst=True )
df_12 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (12).csv',parse_dates=['Date'], dayfirst=True )
df_13 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (13).csv',parse_dates=['Date'], dayfirst=True )
df_14 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (14).csv',parse_dates=['Date'], dayfirst=True )
df_15 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (15).csv',parse_dates=['Date'], dayfirst=True )
df_16 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (16).csv',parse_dates=['Date'], dayfirst=True )
df_17 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (17).csv',parse_dates=['Date'], dayfirst=True )
df_18 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (18).csv',parse_dates=['Date'], dayfirst=True )

In [12]:
df_0 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (0).csv',parse_dates=['Date'], dayfirst=True )
df_1 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (1).csv',parse_dates=['Date'], dayfirst=True )
df_2 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (2).csv',parse_dates=['Date'], dayfirst=True )
df_3 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (3).csv',parse_dates=['Date'], dayfirst=True )
df_4 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (4).csv',parse_dates=['Date'], dayfirst=True )
df_5 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (5).csv',parse_dates=['Date'], dayfirst=True )
df_6 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (6).csv',parse_dates=['Date'], dayfirst=True )
df_7 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (7).csv',parse_dates=['Date'], dayfirst=True )
df_8 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (8).csv',parse_dates=['Date'], dayfirst=True )
df_9 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (9).csv',parse_dates=['Date'], dayfirst=True )
df_10 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (10).csv',parse_dates=['Date'], dayfirst=True )
df_11 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (11).csv',parse_dates=['Date'], dayfirst=True )
df_12 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (12).csv',parse_dates=['Date'], dayfirst=True )
df_13 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (13).csv',parse_dates=['Date'], dayfirst=True )
df_14 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (14).csv',parse_dates=['Date'], dayfirst=True )
df_15 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (15).csv',parse_dates=['Date'], dayfirst=True )
df_16 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (16).csv',parse_dates=['Date'], dayfirst=True )
df_17 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (17).csv',parse_dates=['Date'], dayfirst=True )
df_18 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (18).csv',parse_dates=['Date'], dayfirst=True )

C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_5 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (5).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_6 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (6).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_7 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (7).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_8 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (8).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_9 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (9).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_10 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (10).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_11 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (11).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_12 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (12).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_13 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (13).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:15: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_14 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (14).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_15 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (15).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_16 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (16).csv',parse_dates=['Date'], dayfirst=True )
C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\4237668305.py:18: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_17 = pd.read_csv(r'C:\Users\Hp\Documents\Serie_A\csv_serie_a\I1 (17).csv',parse_dates=['Date'], dayfirst=True )

In [50]:
for i in range(0, 19):
    print(f"df_{i}['Date'] = df_{i}['Date'].dt.strftime('%d/%m/%Y')")

df_0['Date'] = df_0['Date'].dt.strftime('%d/%m/%Y')
df_1['Date'] = df_1['Date'].dt.strftime('%d/%m/%Y')
df_2['Date'] = df_2['Date'].dt.strftime('%d/%m/%Y')
df_3['Date'] = df_3['Date'].dt.strftime('%d/%m/%Y')
df_4['Date'] = df_4['Date'].dt.strftime('%d/%m/%Y')
df_5['Date'] = df_5['Date'].dt.strftime('%d/%m/%Y')
df_6['Date'] = df_6['Date'].dt.strftime('%d/%m/%Y')
df_7['Date'] = df_7['Date'].dt.strftime('%d/%m/%Y')
df_8['Date'] = df_8['Date'].dt.strftime('%d/%m/%Y')
df_9['Date'] = df_9['Date'].dt.strftime('%d/%m/%Y')
df_10['Date'] = df_10['Date'].dt.strftime('%d/%m/%Y')
df_11['Date'] = df_11['Date'].dt.strftime('%d/%m/%Y')
df_12['Date'] = df_12['Date'].dt.strftime('%d/%m/%Y')
df_13['Date'] = df_13['Date'].dt.strftime('%d/%m/%Y')
df_14['Date'] = df_14['Date'].dt.strftime('%d/%m/%Y')
df_15['Date'] = df_15['Date'].dt.strftime('%d/%m/%Y')
df_16['Date'] = df_16['Date'].dt.strftime('%d/%m/%Y')
df_17['Date'] = df_17['Date'].dt.strftime('%d/%m/%Y')
df_18['Date'] = df_18['Date'].dt.strftime('%d/%m/%Y')

In [13]:
df_0['Date'] = df_0['Date'].dt.strftime('%d/%m/%Y')
df_1['Date'] = df_1['Date'].dt.strftime('%d/%m/%Y')
df_2['Date'] = df_2['Date'].dt.strftime('%d/%m/%Y')
df_3['Date'] = df_3['Date'].dt.strftime('%d/%m/%Y')
df_4['Date'] = df_4['Date'].dt.strftime('%d/%m/%Y')
df_5['Date'] = df_5['Date'].dt.strftime('%d/%m/%Y')
df_6['Date'] = df_6['Date'].dt.strftime('%d/%m/%Y')
df_7['Date'] = df_7['Date'].dt.strftime('%d/%m/%Y')
df_8['Date'] = df_8['Date'].dt.strftime('%d/%m/%Y')
df_9['Date'] = df_9['Date'].dt.strftime('%d/%m/%Y')
df_10['Date'] = df_10['Date'].dt.strftime('%d/%m/%Y')
df_11['Date'] = df_11['Date'].dt.strftime('%d/%m/%Y')
df_12['Date'] = df_12['Date'].dt.strftime('%d/%m/%Y')
df_13['Date'] = df_13['Date'].dt.strftime('%d/%m/%Y')
df_14['Date'] = df_14['Date'].dt.strftime('%d/%m/%Y')
df_15['Date'] = df_15['Date'].dt.strftime('%d/%m/%Y')
df_16['Date'] = df_16['Date'].dt.strftime('%d/%m/%Y')
df_17['Date'] = df_17['Date'].dt.strftime('%d/%m/%Y')
df_18['Date'] = df_18['Date'].dt.strftime('%d/%m/%Y')

In [14]:
# Creare una lista di DataFrame
dfs = [globals()[f"df_{i}"] for i in range(19)]

# Concatenare i DataFrame
concatenated_df = pd.concat(dfs, ignore_index=True)

In [33]:
concatenated_df_important = concatenated_df[['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG',
                                              'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 
                                              'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR','B365H','B365D','B365A']]

In [23]:
concatenated_df_important.isna()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6960,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6961,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6962,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6963,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6964,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [26]:
concatenated_df_important.isna().sum().sort_values(ascending=False).head(40)

HST         20
HS          20
AST         20
AS          20
AC          16
HC          16
AF          16
HF          16
B365D       13
B365H       13
B365A       13
HTR          7
HTAG         7
HTHG         7
HY           7
AY           6
HR           6
AR           6
Date         5
FTR          5
FTAG         5
FTHG         5
AwayTeam     5
HomeTeam     5
Div          5
dtype: int64

In [34]:
concatenated_df_important = concatenated_df_important.drop(columns=['Time'])
concatenated_df_important = concatenated_df_important.dropna(subset=['HomeTeam'])
#concatenated_df_important = concatenated_df_important.dropna(subset=['HTAG', 'AST','HY'])
concatenated_df_important['Date'] = pd.to_datetime(concatenated_df_important['Date'])

C:\Users\Hp\AppData\Local\Temp\ipykernel_17440\1143043079.py:4: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  concatenated_df_important['Date'] = pd.to_datetime(concatenated_df_important['Date'])

In [35]:
# Selezionare solo le righe che contengono almeno un valore NaN
df_con_nan = concatenated_df_important[concatenated_df_important.isna().any(axis=1)]

# Stampare il nuovo DataFrame
df_con_nan

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A
583,I1,2022-01-10,Torino,Fiorentina,4.0,0.0,H,3.0,0.0,H,...,12.0,1.0,5.0,2.0,2.0,0.0,0.0,NaN,NaN,NaN
795,I1,2020-10-18,Udinese,Parma,3.0,2.0,H,1.0,1.0,D,...,11.0,11.0,2.0,3.0,2.0,0.0,0.0,NaN,NaN,NaN
797,I1,2020-10-19,Verona,Genoa,0.0,0.0,D,0.0,0.0,D,...,15.0,14.0,2.0,1.0,4.0,0.0,0.0,NaN,NaN,NaN
2297,I1,2016-08-28,Sassuolo,Pescara,0.0,3.0,A,NaN,NaN,NaN,...,21.0,2.0,7.0,2.0,2.0,0.0,0.0,1.62,3.75,6.00
3288,I1,2015-03-02,Roma,Juventus,1.0,1.0,D,0.0,0.0,D,...,16.0,1.0,5.0,NaN,5.0,1.0,0.0,3.30,3.30,2.25
3836,I1,2012-09-23,Cagliari,Roma,0.0,3.0,A,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.10,3.50,2.20
4890,I1,2011-04-17,Chievo,Bologna,2.0,0.0,H,1.0,0.0,H,...,21.0,5.0,5.0,2.0,2.0,1.0,0.0,NaN,NaN,NaN
4892,I1,2011-04-17,Genoa,Brescia,3.0,0.0,H,0.0,0.0,D,...,16.0,6.0,5.0,2.0,3.0,0.0,0.0,NaN,NaN,NaN
5305,I1,2010-05-09,Bologna,Catania,1.0,1.0,D,1.0,0.0,H,...,7.0,3.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN
6550,I1,2005-10-26,Lazio,Chievo,2.0,2.0,D,1.0,0.0,H,...,NaN,NaN,NaN,1.0,3.0,0.0,0.0,2.00,3.00,4.00
6597,I1,2005-12-04,Fiorentina,Juventus,1.0,2.0,A,1.0,1.0,D,...,NaN,NaN,NaN,0.0,3.0,0.0,0.0,2.87,3.00,2.30
6598,I1,2005-12-04,Lazio,Siena,3.0,2.0,H,1.0,0.0,H,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.80,3.00,4.33
6599,I1,2005-12-04,Lecce,Roma,2.0,2.0,D,0.0,2.0,A,...,NaN,NaN,NaN,2.0,3.0,0.0,0.0,3.25,3.00,2.10
6600,I1,2005-12-04,Palermo,Cagliari,2.0,2.0,D,2.0,0.0,H,...,NaN,NaN,NaN,5.0,3.0,0.0,0.0,1.61,3.25,5.50
6601,I1,2005-12-04,Reggina,Parma,2.0,1.0,H,2.0,1.0,H,...,NaN,NaN,NaN,2.0,3.0,0.0,1.0,1.90,3.00,3.80
6602,I1,2005-12-04,Sampdoria,Empoli,2.0,0.0,H,0.0,0.0,D,...,NaN,NaN,NaN,1.0,1.0,0.0,0.0,1.66,3.20,5.00
6603,I1,2005-12-04,Treviso,Messina,0.0,0.0,D,0.0,0.0,D,...,NaN,NaN,NaN,2.0,3.0,0.0,1.0,2.40,2.75,3.00
6604,I1,2005-12-04,Udinese,Livorno,0.0,2.0,A,0.0,1.0,A,...,NaN,NaN,NaN,2.0,3.0,0.0,0.0,1.80,3.00,4.33
6605,I1,2005-12-10,Fiorentina,Treviso,1.0,0.0,H,0.0,0.0,D,...,34.0,2.0,3.0,1.0,4.0,0.0,0.0,1.28,5.00,10.00
6606,I1,2005-12-10,Siena,Empoli,1.0,0.0,H,1.0,0.0,H,...,20.0,3.0,6.0,4.0,3.0,0.0,0.0,2.10,3.00,3.75
6611,I1,2005-12-11,Messina,Chievo,2.0,0.0,H,2.0,0.0,H,...,NaN,NaN,NaN,1.0,1.0,0.0,1.0,2.60,2.87,2.90
6615,I1,2005-12-17,Lazio,Juventus,1.0,1.0,D,1.0,1.0,D,...,30.0,3.0,7.0,2.0,3.0,0.0,0.0,6.00,3.20,1.66
6616,I1,2005-12-17,Treviso,Lecce,2.0,1.0,H,1.0,0.0,H,...,26.0,2.0,3.0,4.0,4.0,0.0,1.0,2.50,3.00,2.90
6792,I1,2006-04-09,Parma,Reggina,4.0,0.0,H,2.0,0.0,H,...,15.0,1.0,7.0,0.0,0.0,1.0,1.0,NaN,NaN,NaN
6798,I1,2006-04-15,Empoli,Siena,2.0,1.0,H,2.0,0.0,H,...,19.0,4.0,5.0,2.0,2.0,0.0,0.0,NaN,NaN,NaN

In [36]:
# Ordinare il DataFrame in base alla colonna "Date" in ordine discendente
df_importanti = concatenated_df_important.sort_values(by='Date', ascending=False)
df_importanti

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A
6964,I1,2023-11-12,Inter,Frosinone,2.0,0.0,H,1.0,0.0,H,...,16.0,9.0,4.0,0.0,1.0,0.0,0.0,1.18,8.00,13.00
6962,I1,2023-11-12,Udinese,Atalanta,1.0,1.0,D,1.0,0.0,H,...,13.0,7.0,7.0,2.0,3.0,0.0,0.0,3.75,3.50,2.00
6961,I1,2023-11-12,Fiorentina,Bologna,2.0,1.0,H,1.0,1.0,D,...,15.0,0.0,3.0,2.0,2.0,0.0,0.0,2.00,3.40,3.80
6960,I1,2023-11-12,Napoli,Empoli,0.0,1.0,A,0.0,0.0,D,...,13.0,8.0,3.0,1.0,1.0,0.0,0.0,1.22,7.00,11.00
6963,I1,2023-11-12,Lazio,Roma,0.0,0.0,D,0.0,0.0,D,...,13.0,4.0,1.0,3.0,4.0,0.0,0.0,3.00,3.00,2.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6473,I1,2005-08-28,Siena,Cagliari,2.0,1.0,H,1.0,1.0,D,...,19.0,4.0,4.0,2.0,2.0,1.0,0.0,2.20,3.00,3.10
6474,I1,2005-08-28,Udinese,Empoli,1.0,0.0,H,1.0,0.0,H,...,12.0,6.0,5.0,2.0,1.0,0.0,0.0,1.57,3.25,6.00
6467,I1,2005-08-28,Ascoli,Milan,1.0,1.0,D,0.0,0.0,D,...,16.0,0.0,5.0,2.0,1.0,0.0,0.0,7.50,3.75,1.40
6465,I1,2005-08-27,Fiorentina,Sampdoria,2.0,1.0,H,2.0,0.0,H,...,23.0,9.0,3.0,1.0,4.0,0.0,0.0,2.20,2.87,3.25
6466,I1,2005-08-27,Livorno,Lecce,2.0,1.0,H,1.0,1.0,D,...,21.0,9.0,2.0,2.0,3.0,0.0,0.0,1.90,2.90,4.00

In [62]:
# Esporta il DataFrame in un file CSV
df_importanti.to_csv(r'C:\Users\Hp\Downloads\partite_serie_A.csv', index=True)